extends SceneTree

# Checks the Blender blockout importer against maps/blockout.example.json.
#   godot --headless --path . --script res://tests/blockout_import.gd

var checks := 0
var failures := 0

func check(condition: bool, message: String) -> void:
	checks += 1
	if not condition:
		failures += 1
		printerr("FAIL: ", message)

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	var data := BlockoutImporter.read("res://maps/blockout.example.json")
	check(not data.is_empty(), "example blockout parses")
	var b := MapBuilder.new()
	var errors := BlockoutImporter.build(b, data)
	check(errors.is_empty(), "example builds without errors: %s" % [errors])
	# floor + mirrored wall (2) + ramp + mirrored column (2)
	check(b.solids.size() == 6, "six solids built (got %d)" % b.solids.size())
	check(b.decor.size() == 1, "one decor block built (got %d)" % b.decor.size())
	var kinds := {}
	for s in b.solids:
		kinds[s.kind] = kinds.get(s.kind, 0) + 1
	check(kinds.get("ramp", 0) == 1 and kinds.get("cylinder", 0) == 2, "ramp and mirrored cylinder present")
	var tags := []
	for s in b.solids:
		tags.append(s.tag)
	check(tags.has("plaza_wall") and tags.has("plaza_wall_e"), "mirrored wall carries _e tag")
	for s in b.solids:
		var box: AABB = s.aabb
		check(is_equal_approx(fposmod(box.position.x, MapBuilder.SNAP), 0.0) or is_equal_approx(fposmod(box.position.x, MapBuilder.SNAP), MapBuilder.SNAP), "%s sits on the 0.25 m grid" % s.tag)
	var graph := BlockoutImporter.graph(data)
	check(graph.nodes.size() == 2 and graph.links.size() == 1, "waypoint graph has 2 nodes and 1 link")
	check(b.sunken.is_empty(), "no sunken area without a deep walk floor")
	var bad := BlockoutImporter.build(MapBuilder.new(), {"objects": [
		{"kind": "ramp", "tag": "r", "min": [0, 0, 0], "max": [4, 2, 4], "dir": "up"},
		{"kind": "block", "tag": "x"},
		{"kind": "teapot", "tag": "t", "min": [0, 0, 0], "max": [1, 1, 1]},
	]})
	check(bad.size() == 3, "three malformed objects are reported (got %d)" % bad.size())
	check(BlockoutImporter.read("res://maps/does_not_exist.json").is_empty(), "missing file reads as empty")
	check_yard()
	check_layout_dump()
	print("blockout import: %d checks, %d failures" % [checks, failures])
	quit(1 if failures > 0 else 0)

# Replace-mode settings for the Test Yard (generated by tools/blender/generate.py).
func check_yard() -> void:
	var data := BlockoutImporter.read("res://maps/yard.blockout.json")
	check(data.get("mode", "") == "replace", "yard is a replace-mode blockout")
	var r := BlockoutImporter.resolve(data)
	check(r.errors.is_empty(), "yard resolves without errors: %s" % [r.errors])
	check(r.points.size() == 5, "yard has five capture points (got %d)" % r.points.size())
	check(r.goal_names == ["A", "B", "C", "e_B", "e_A"], "capture points are ordered west to east: %s" % [r.goal_names])
	check(r.spawn_nodes == ["S", "e_S"], "spawn nodes are west then east: %s" % [r.spawn_nodes])
	check(is_equal_approx(r.spawn_x, 57.0) and is_equal_approx(r.depot_limit, 53.0), "yard spawn and depot settings read from file")
	check(r.bounds == Rect2(-62, -32, 124, 64), "yard bounds read from file")
	check(r.graph.nodes.has("e_dk") and r.graph.nodes.e_dk.x > 0.0, "mirrored waypoints exist on the east side")
	var reach := _reachable(r.graph, "S")
	check(reach.size() == r.graph.nodes.size(), "depot reaches every yard waypoint (%d/%d)" % [reach.size(), r.graph.nodes.size()])
	for goal in r.goal_names:
		check(reach.has(goal), "depot reaches capture point %s" % goal)
	var b := MapBuilder.new()
	var errors := BlockoutImporter.build(b, data)
	check(errors.is_empty(), "yard builds without errors: %s" % [errors])
	var bad := BlockoutImporter.resolve({"settings": {}, "waypoints": [], "links": []})
	check(bad.errors.size() >= 2, "replace without points or spawns is refused (%d errors)" % bad.errors.size())

# When maps/layout.blockout.json exists (written by tools/export_layout.gd), importing it must rebuild the
# built-in map exactly: same solids, same graph, same points. Skipped when the file is absent.
func check_layout_dump() -> void:
	var data := BlockoutImporter.read("res://maps/layout.blockout.json")
	if data.is_empty():
		print("  (maps/layout.blockout.json not present; skipping built-in map equivalence)")
		return
	var reference := MapBuilder.new()
	MapLayout.build(reference)
	var rebuilt := MapBuilder.new()
	var errors := BlockoutImporter.build(rebuilt, data)
	check(errors.is_empty(), "layout dump builds without errors")
	check(rebuilt.solids.size() == reference.solids.size(), "layout dump rebuilds %d solids (got %d)" % [reference.solids.size(), rebuilt.solids.size()])
	check(rebuilt.decor.size() == reference.decor.size(), "layout dump rebuilds %d decor blocks (got %d)" % [reference.decor.size(), rebuilt.decor.size()])
	var r := BlockoutImporter.resolve(data)
	check(r.errors.is_empty(), "layout dump resolves: %s" % [r.errors])
	check(r.points == MapLayout.points(), "layout dump capture points match MapLayout")
	var ref_graph := MapLayout.graph()
	check(r.graph.nodes.size() == ref_graph.nodes.size() and r.graph.links.size() == ref_graph.links.size(), "layout dump graph matches (%d nodes, %d links)" % [ref_graph.nodes.size(), ref_graph.links.size()])
	check(rebuilt.sunken.size() == reference.sunken.size(), "layout dump keeps the sunken trench area")

func _reachable(graph: Dictionary, start: String) -> Dictionary:
	var adj := {}
	for l in graph.links:
		adj[l[0]] = adj.get(l[0], []) + [l[1]]
		adj[l[1]] = adj.get(l[1], []) + [l[0]]
	var seen := {start: true}
	var queue := [start]
	while not queue.is_empty():
		var n: String = queue.pop_front()
		for m in adj.get(n, []):
			if not seen.has(m):
				seen[m] = true
				queue.append(m)
	return seen
